name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/workflow-B.yml
    with:
      input1: test1
      input2: test2
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
