name: "My workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: failurestep
        name: failurestep
        run: exit 1
      - id: onfailurestep
        name: onfailurestep
        if: ${{ failure() && steps.failurestep.conclusion == 'failure' }}
        run: echo previous step failed
