name: "My workflow"
on:
  workflow_dispatch:
jobs:
  getcommit:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - id: lastcommit
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: martin2176
          repo: helloworld1
          branch: dev  
      - id: printcommit
        run: echo ${{ steps.lastcommit.outputs.shorthash }}
