name: "My workflow"
on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
      - name: Run the scripts
        run: pwd 
        env:
         MY_ENV_VAR: ${{ format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat') }}

        


