name: "My workflow"
on:
  workflow_dispatch:
jobs:
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    steps:
     - name: curlstep
       run: curl http://localhost:8080
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: nginx
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 8080:80
