on:
  workflow_dispatch:
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
   - id: env-setup
     run: | 
      echo "env_token=production" >> "$GITHUB_OUTPUT"
      echo "env_domain=example.com" >> "$GITHUB_OUTPUT"

