name: "My workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output }}
      output_2: ${{ steps.gen_output.outputs.output }}
      output_3: ${{ steps.gen_output.outputs.output }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output=${version}" >> "$GITHUB_OUTPUT" 
          echo "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
       - run: echo '${{ toJSON(needs.job1.outputs) }}'
