on:
  workflow_dispatch:
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
   - id: env-setup
     name: env-setip
     run: | 
      {
      "env_token=production"
      "env_domain=example.com"
      } >> $GITHUB_OUTPUT
   - id: print-env
     name: print-env
     run: |
      echo "${{ steps.env-setup.outputs.env_token }}"
      echo "${{ steps.env-setup.outputs.env_domain }}"
