name: "My workflow"
on:
  workflow_dispatch:
jobs:
  getcommit:
    runs-on: ubuntu-latest
    steps:
      - id: lastcommit
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: martin
          repo: helloworld1
          branch: main  
      - id: printcommit
        run: echo ${{ steps.lastcommit.outputs.shorthash }}
