name: "My workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
      output_2: ${{ steps.gen_output.outputs.output_2 }}
      output_3: ${{ steps.gen_output.outputs.output_3 }}    

    strategy:
      matrix:
        version: [1, 2, 4]
    steps:
      - name: Generate_output ${{ strategy.job-index }}
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output=${version}" >> "$GITHUB_OUTPUT" 
          echo "$GITHUB_OUTPUT"
          hostname
          echo ${{ strategy.job-index }}
