name: "My workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: output1
        run: echo hello
      -  id: output2
         run: echo "${{ toJSON(env) }}"
