name: "My workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output }}
      output_2: ${{ steps.gen_output.outputs.output }}
      output_3: ${{ steps.gen_output.outputs.output }}
    strategy:
      matrix:
        version: [1, 2, 4]
    steps:
      - name: Generate_output_${{ strategy.job-index }}
        id: gen_output_${{ strategy.job-index }}
        run: |
          version="${{ matrix.version }}"
          echo "output=${version}" >> "$GITHUB_OUTPUT" 
          echo "$GITHUB_OUTPUT"
          hostname
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
       - run: |
          echo '${{ toJSON(needs.job1.outputs) }}'
          echo '${{ needs.job1.output_1) }}'
          echo '${{ needs.job1.output_2) }}'
          echo '${{ needs.job1.output_3) }}'
