name: "My workflow"
on:
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    services:
    # Label used to access the service container
     redis:
      # Docker Hub image
       image: redis

