name: "My workflow"
on:
  workflow_dispatch:
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: |
         echo ${{ vars.FOO1 }}
         echo $foo1
        env:
         foo1: ${{ vars.FOO1 }}
        
