on: workflow_dispatch
env:
 env_var: ${{ vars.FOO }}
jobs:
  if-Windows-else:
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: always
        run: echo "variable from shell environment $env_var"
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
        
