name: "My workflow"
on:
  workflow_dispatch:
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:16-bullseye
  steps:
    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
    # Service containers to run with `container-job`
  services:
    # Label used to access the service container
    redis:
      # Docker Hub image
      image: redis
