on:
  workflow_dispatch:
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
   - id: env-setup1
     name: env-setip1
     run: | 
      echo "env_token=production" >> $GITHUB_OUTPUT
   - id: env-setup2
     name: env-setip2
     run: | 
      echo "env_token=development"  >> $GITHUB_OUTPUT
   - id: print-env
     name: print-env
     run: |
      echo "${{ steps.env-setup1.outputs.env_token }}"
      echo "${{ steps.env-setup2.outputs.env_token }}"
