on: workflow_dispatch
name: compositeaction
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      #- uses: actions/checkout@v4
      #  name: step1
      - id: foo
        uses: martin2176/helloworld1@main
        with:
          who-to-greet: 'Mona the Octocat'
        name: step2
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
        name: step3
