on: workflow_dispatch
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
     - name: Set the value in bash
       id: step_one
       run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo $GITHUB_ENV
        echo $envfile
        echo $envfile1
        echo  ${{ github.env }}
        echo ${{ runner.os }}
       env:
        envfile: ${{github.env}}
        envfile1: ${{ runner.os }}
