on: workflow_dispatch
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
     - name: Set the value in bash
       id: step_one
       run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://example.com
            echo EOF
          } >> "$GITHUB_ENV"
