on: workflow_dispatch
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
     - name: Set the value in bash
       id: step_one
       run: |
        echo $PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
     - name: getvalue
       id: step_two
       run: |
        echo $PATH
