on: workflow_dispatch
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
     - name: Set the value in bash
       id: step_one
       run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo $GITHUB_ENV
        echo $envfile
       env:
        envfile: $GITHUB_ENV
