on:
  workflow_dispatch
jobs:
  print_context:
    if: ${{ 1 == 2 }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
    
  print_context2:
    if: ${{ 1 == 1 }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
