on:
  workflow_dispatch:
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "again inside group"
            echo "::add-mask::Mona The Octocat"
            echo "::endgroup::"
            echo "::add-mask::"Mona The Octocat""
  bash-example1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"



   
