name: calledworkflow
on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string    
    secrets:
      token:
        required: true

jobs:
  printinputfromcallingworkflow:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo {{ inputs.input1 }}
       echo {{ inputs.input2 }}
       echo {{ secrets.token }}
