on:
  workflow_dispatch:
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "again inside group"
            echo "::add-mask::Mona The Octocat"
            echo "::endgroup::"

   
